# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jdavis <jdavis@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/06/10 11:20:52 by jdavis            #+#    #+#              #
#    Updated: 2021/06/10 13:00:50 by jdavis           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

all:
	gcc -Wall -Wextra -Werror -o $(NAME) ft_display_file.c
	
clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)